version: 2
jobs:
  test:
    docker:
      - image: ruby
      - image: postgres
    steps:
      - checkout
      - run: bundle install
      - run: rails db:create
      - run: rails db:migrate
      - run: rails test
