version: 2
jobs:
  build:
    docker:
      - image: ruby:2.5.1
      - image: postgres
    steps:
      - checkout
      - run: bundle install
      - run: rails db:create
      - run: rails db:migrate
      - run: rails test
