version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    steps:
      - checkout
      - run: bundle install
      - run: rails db:create
      - run: rails db:migrate
      - run: rails test
